### ISSUE TITLE
Error determining manifest MIME type for docker image in registry

### ISSUE THREAD

**Issue by goern** [thoth-station/analyzer#48]
**Describe the bug**
```
thoth.analyzer.command.CommandError: Command exited with non-zero status code (1): time="2018-09-24T09:24:08Z" level=fatal msg="Error determining manifest MIME type for docker://docker-registry-default.cloud.registry.u.rh.com/aicoe-x-y/x-y-image-general:latest: Error reading manifest latest in docker-registry-default.cloud.registry.u.rh.com/aicoe-x-y/x-y-image-general: manifest unknown: manifest unknown" 
```

**To Reproduce**
Run `https://jupyterhub-dh-prod-jupyterhub.cloud.dh.u.rh.com/user/cgoern/notebooks/Analyse%20all%20containers.ipynb`

**Expected behavior**
Image should be analysed by Thoth

**Additional context**
n/a

**Comment by ace2107** [comment]
The following error occurs because the imagestreams have no image labels(Not even the default :latest)
If the image in the registry had a label this will not occur

**Comment by fridex** [comment]
I think this is no longer relevant - the error is propagated directly from skopeo, its not in our scope.
